# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:

    # выключает кеширование грантов в сессии, чтобы можно было отнимать/выдавать людям права без перелогина
    # добавляет один поход в базу на каждой странице
    always_authenticate_before_granting: true

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:            .*
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                default_target_path: my_clients
            logout:
                path:           /logout
                target:         /login
            anonymous:          true
            switch_user:        true

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, SONATA]

        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT # if you are not using acl then this line must be uncommented
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT
            - ROLE_APP_SHELTER_ROOM_ADMIN_LIST
            - ROLE_APP_SHELTER_ROOM_ADMIN_CREATE
            - ROLE_APP_SHELTER_ROOM_ADMIN_DELETE
