sonata_user:
  security_acl: false
  manager_type: orm # can be orm or mongodb
  class:
    user: App\Entity\User
  #    profile:
  #        menu:
  #            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
  #            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
  admin: # Admin Classes
    user:
      class: App\Sonata\UserBundle\Admin\UserAdmin
      controller: SonataAdminBundle:CRUD
      translation: SonataUserBundle
  impersonating:
    route: sonata_admin_dashboard
  resetting:
    email:
      address: sonata@localhost
      sender_name: Sonata Admin